Work
ClevertecFrontendLab/Salt-Upon-Wounds pull request #2
Opened 2023-02-22 14:41 UTC by Salt-Upon-Wounds

2023-02-22 14:47 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 75%.
Общее количество тестов: 16.
Количество непройденных тестов: 4.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677077250/search-result-not-found.png)

2023-02-22 16:12 UTC, Ivan6813 requested changes

2023-02-22 16:12 UTC, Ivan6813 commented on src/components/aside/aside.jsx
> +                                                                <span className="options__counter" data-test-id={`${window.innerWidth <= 768 ? 'burger' : 'navigation'}-book-count-for-${el.path}`}>
window.innerWidth <= 768 - очень странное решение, подумай как можно по другому это реализовать

2023-02-22 16:12 UTC, Ivan6813 commented on src/components/books-list/books-list.jsx
>              {
категория Все книги в неактивном состоянии не должна отличатся от других неактивных категорий

![msedge_uSCe7FNELo](https://user-images.githubusercontent.com/79784960/220685884-8988d0fb-9b52-438e-9da0-87446e4300c9.png)

2023-02-22 16:12 UTC, Ivan6813 commented on src/components/books-list/books-list.jsx
> +                status === 1 && booksToRender.length > 0 &&
кнопка сортировки не по макету. Посмотри как она выглядит на макете

![msedge_Zz8w0YOd1I](https://user-images.githubusercontent.com/79784960/220686076-b6029bf4-ca6f-4da9-a5a7-b5569bdaaf1d.png)

2023-02-22 16:12 UTC, Ivan6813 commented on src/components/books-list/books-list.jsx
>                          <button type='submit' className='search__btn' onClick={openSearch} data-test-id='button-search-open'>
когда на инпуте фокус,то иконка лупы должна иметь другой цвет, сверься с макетом

![msedge_R1vb7ziatU](https://user-images.githubusercontent.com/79784960/220686356-aec44c40-2502-48b7-b006-2216e2e84433.png)

2023-02-23 13:10 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 87%.
Общее количество тестов: 16.
Количество непройденных тестов: 2.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/active-category-programming.png)
***
**bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Salt-Upon-Wounds/1677157855/search-result-not-found.png)

2023-02-23 13:57 UTC, Ivan6813 approved these changes

2023-02-23 13:58 UTC, merged